<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Enarro</RootNamespace>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <!-- API -->
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
        <PackageReference Include="CoreKernel.Functional" Version="2.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4" />
        
        <!-- Serilog -->
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        
        <!-- Password Hashing -->
        <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Enarro.ServiceDefaults\Enarro.ServiceDefaults.csproj" />
      <ProjectReference Include="..\Enarro.Application\Enarro.Application.csproj" />
      <ProjectReference Include="..\Enarro.Persistence\Enarro.Persistence.csproj" />
      <ProjectReference Include="..\Enarro.Infrastructure\Enarro.Infrastructure.csproj" />
    </ItemGroup>

</Project>
