using Enarro.Domain.Conversation;
using Enarro.Persistence.Constants;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Enarro.Persistence.Configurations;

/// <summary>
/// EF Core configuration for <see cref="ConversationMessage"/>.
/// </summary>
internal class ConversationMessageConfiguration : IEntityTypeConfiguration<ConversationMessage>
{
    public void Configure(EntityTypeBuilder<ConversationMessage> builder)
    {
        builder.ToTable(TableName.ConversationMessages);

        builder.HasKey(m => m.Id);

        // Id is auto-generated by the database
        builder.Property(m => m.Id)
            .ValueGeneratedOnAdd();

        builder.HasIndex(m => m.SessionId);
        builder.HasIndex(m => new { m.SessionId, m.CreatedAt });

        builder.Property(m => m.SessionId).HasMaxLength(64).IsRequired();
        builder.Property(m => m.Role).HasMaxLength(20).IsRequired();
        builder.Property(m => m.Content).IsRequired();
    }
}
